#!/data/data/com.termux/files/usr/bin/bash

# 配色定义
BLUE='\033[0;34m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
MAGENTA='\033[0;35m'
RED='\033[0;31m'
WHITE='\033[0;37m'
RESET='\033[0m'  # 重置颜色
BOLD='\033[1m'
ORANGE='\033[0;33m'
SAKURA_PINK='\033[38;5;218m'

DEFAULT_PAK_DIR="pak"

# 清屏
clear

# 动画效果 - 进度条
show_loading() {
    local pid=$!
    local delay='.'
    local spinstr='|/-\\'
    local temp
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        spinstr=$temp${spinstr%"$temp"}
        sleep 0.1
        printf "\r"
    done
    echo "    完成!"
}

# 显示主菜单
show_main_menu() {
    # 读取并显示菜单信息
    if [ -f "菜单信息" ]; then
        while IFS= read -r line; do
            echo "$line"
        done < "菜单信息"
    else
        echo -e "${RED}未找到菜单信息文件！${RESET}"
    fi
    echo -e "${GREEN}1) 自动美化工具${RESET}"
    echo -e "${BLUE}2) 解包工具${RESET}"
    echo -e "${MAGENTA}3) 打包工具${RESET}"
    echo -e "${SAKURA_PINK}4) 自动搜索特征值${RESET}"
    echo -e "${YELLOW}5) 搜索工具${RESET}"
    echo -e "${RED}6) 重置文件夹${RESET}"
    echo -e "${CYAN}7) 退出工具${RESET}"
    echo -n -e "${BOLD}请选择操作的序号：${RESET}"
}

# 获取 pak 文件列表
list_pak_files() {
    local dir="$1"
    local files=()
    for file in "$dir"/*.pak; do
        if [ -f "$file" ]; then
            files+=("$file")
        fi
    done
    echo "${files[@]}"
}

# 选择 pak 文件
select_pak_file() {
    local dir="$1"
    local files=($(list_pak_files "$dir"))
    if [ ${#files[@]} -eq 0 ]; then
        echo -e "${RED}目录 \"$dir\" 中没有找到 .pak 文件${RESET}"
        return 1
    fi
    echo -e "${YELLOW}请选择要操作的 .pak 文件：${RESET}"
    for i in "${!files[@]}"; do
        echo -e "${YELLOW}$((i+1))) ${files[$i]}${RESET}"
    done
    echo -n -e "${BOLD}请输入选项：${RESET}"
    read -r choice
    if [[ "$choice" -ge 1 && "$choice" -le "${#files[@]}" ]]; then
        selected_file="${files[$((choice-1))]}"
        echo -e "${GREEN}你选择了：${selected_file}${RESET}"
        return 0
    else
        echo -e "${RED}无效选择！${RESET}"
        return 1
    fi
}

# 如果指定了目录，则使用该目录，否则使用默认目录
if [ $# -ge 1 ]; then
    PAK_DIR="$1"
    if [ ! -d "$PAK_DIR" ]; then
        echo -e "${RED}目录 \"$PAK_DIR\" 不存在！${RESET}"
        exit 1
    fi
else
    PAK_DIR="$DEFAULT_PAK_DIR"
fi

# 主程序逻辑
while true; do
    show_main_menu
    read -r choice
    echo ""
    case $choice in
        1) 
            clear
            echo -e "${GREEN}自动美化工具${RESET}"
            while true; do
                echo -e "${YELLOW}1) 自动美化(衣服)${RESET}"
                echo -e "${YELLOW}2) 自动美化(衣服图标)${RESET}"
                echo -e "${BLUE}3) 返回主菜单${RESET}"
                echo -n -e "${BOLD}请选择对应序号：${RESET}"
                read -r sub_choice
                case $sub_choice in
                    1) 
                        echo -e "${YELLOW}开始自动美化衣服...${RESET}"
                        ./tools/AutoSwitchSkin
                        show_loading &
                        ;;
                    2) 
                        echo -e "${YELLOW}开始自动美化衣服图标...${RESET}"
                        ./tools/AutoSwitchSkinIcon
                        show_loading &
                        ;;
                    3) 
                        clear
                        break
                        ;;
                    *)
                        echo -e "${RED}请输入 1 到 3 之间的数字！${RESET}"
                        ;;
                esac
            done
            ;;
        2) 
            clear
            echo -e "${BLUE}解包工具${RESET}"
            while true; do
                echo -e "${CYAN}1) dat 解包${RESET}"
                echo -e "${CYAN}2) uexp 解包${RESET}"
                echo -e "${YELLOW}3) 返回主菜单${RESET}"
                echo -n -e "${BOLD}请选择：${RESET}"
                read -r unpack_choice
                case $unpack_choice in
                    1) 
                        if select_pak_file "$PAK_DIR"; then
                            echo -e "${YELLOW}正在解包 .dat 文件...${RESET}"
                            qemu-i386 tools/quickbms tools/Extract.bms "$selected_file" 解包数据/dat
                            show_loading &
                        fi
                        ;;
                    2) 
                        if select_pak_file "$PAK_DIR"; then
                            echo -e "${YELLOW}正在解包 .uexp 文件...${RESET}"
                            ./tools/unpack -a "$selected_file" 解包数据/uexp
                            show_loading &
                        fi
                        ;;
                    3) 
                        clear
                        break
                        ;;
                    *)
                        echo -e "${RED}请输入 1 到 3 之间的数字！${RESET}"
                        ;;
                esac
            done
            ;;
        3) 
            clear
            echo -e "${MAGENTA}打包工具${RESET}"
            while true; do
                echo -e "${CYAN}1) dat 打包${RESET}"
                echo -e "${CYAN}2) uexp 打包${RESET}"
                echo -e "${YELLOW}3) 返回主菜单${RESET}"
                echo -n -e "${BOLD}请选择：${RESET}"
                read -r pack_choice
                case $pack_choice in
                    1) 
                        if select_pak_file "$PAK_DIR"; then
                            echo -e "${YELLOW}正在打包 .dat 文件...${RESET}"
                            qemu-i386 tools/quickbms -w -r -r tools/Pack.bms "$selected_file" 打包/dat
                            show_loading &
                        fi
                        ;;
                    2) 
                        if select_pak_file "$PAK_DIR"; then
                            echo -e "${YELLOW}正在打包 .uexp 文件...${RESET}"
                            ./tools/unpack -a -r "$selected_file" 打包/uexp
                            show_loading &
                        fi
                        ;;
                    3) 
                        clear
                        break
                        ;;
                    *)
                        echo -e "${RED}请输入 1 到 3 之间的数字！${RESET}"
                        ;;
                esac
            done
            ;;
        4) 
            clear
            echo -e "${YELLOW}...${RESET}"
            ./tools/AutoMarker
            ;;
        5) 
            clear
            echo -e "${CYAN}搜索工具${RESET}"
            echo -e "${CYAN}开始搜索...${RESET}"
            ./tools/Search  # 执行载具搜索脚本
            show_loading &
            ;;
        6) 
            clear
            echo -e "${YELLOW}重置文件夹...${RESET}"
            ./tools/ResetFolder
            ;;
        7) 
            echo -e "${RED}退出工具...${RESET}"
            exit 0
            ;;
        *)
            echo -e "${RED}请输入 1 到 7 之间的数字！${RESET}"
            ;;
    esac
done